"""empty message

Revision ID: 490e1ea56990
Revises: fd92a8db59d9
Create Date: 2025-10-08 14:51:12.814868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490e1ea56990'
down_revision = 'fd92a8db59d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
